---
version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /mnt/appdata/jellyfin:/config
      - /mnt/storage:/data:ro
      - /dev/shm:/transcode
    ports:
      - 2285:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.rdu.dotsandstuff.dev
    hostname: jf-rdu
    restart: unless-stopped
  abs:
    image: advplyr/audiobookshelf
    container_name: abs
    volumes:
      - /mnt/storage/audiobooks/library:/audiobooks:ro
      - /mnt/storage/audiobooks/podcasts:/podcasts
      - /mnt/appdata/audiobookshelf/metadata:/metadata
      - /mnt/appdata/audiobookshelf/config:/config
    ports:
      - 2284:80
    restart: unless-stopped